const express = require('express');
const router = express.Router();
const RendezVousController = require('../controllers/rendezVousController');

router.delete('/supprimerprestation', RendezVousController.supprimerPrestationRendezVous);
router.post('/ajouterprestation', RendezVousController.ajouterPrestationRendezVous);
router.post('/changeravancement', RendezVousController.changerAvancementRendezVous);
router.get('/enattente/:idclient', RendezVousController.getAllRendezVousEnAttenteByClient);
router.get('/avalider', RendezVousController.getAllRendezVousEnAttente);
router.post('/confirmation', RendezVousController.confirmerNouvelleDate);
router.get('/proposition/:idclient', RendezVousController.getRendezVousAConfirmer);
router.post('/proposer', RendezVousController.proposerNouvelleDate);
router.post('/valider', RendezVousController.validerRendezVous);
router.get('/mecaniciens/:date', RendezVousController.getMecaniciensDisponibles);
router.post('/', RendezVousController.createRendezVous);
router.get('/detailsdevis/:idrendezvous', RendezVousController.getDetailsDevisByRendezVous);
router.get('/acceptes/:idclient', RendezVousController.getAllRendezVousValidesByClient);
router.post('/validesmecanicien', RendezVousController.getAllRendezVousValidesByMecanicien);
router.post('/valides', RendezVousController.getAllRendezVousValides);
router.get('/nonvalides', RendezVousController.getAllRendezVousNonValides);
module.exports = router;
